apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - backend-servicemonitor.yaml
  - backend-prometheusrule.yaml

configMapGenerator:
  - name: grafana-dashboard-mainplatform-backend
    namespace: monitoring
    files:
      - dashboards/mainplatform-backend.json
    options:
      labels:
        grafana_dashboard: "1"

generatorOptions:
  disableNameSuffixHash: true