apiVersion: v1
kind: Secret
metadata:
  name: mainplatform-secret
  namespace: mainplatform
type: Opaque
stringData:
  POSTGRES_PASSWORD: app_password
  DATABASE_URL: postgresql+psycopg://app:app_password@postgres:5432/app