apiVersion: v1
kind: ServiceAccount
metadata:
  name: mainplatform-backend
  namespace: mainplatform
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mainplatform-postgres
  namespace: mainplatform
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-vault-sync
  namespace: monitoring