apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault
  namespace: monitoring
spec:
  address: http://vault.vault.svc.cluster.local:8200
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: monitoring
  namespace: monitoring
spec:
  vaultConnectionRef: vault
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: monitoring-vault-sync
    serviceAccount: monitoring-vault-sync
    audiences:
      - vault
    tokenExpirationSeconds: 600
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  vaultAuthRef: monitoring
  mount: secret
  type: kv-v2
  path: monitoring/grafana
  refreshAfter: 1m
  hmacSecretData: true
  destination:
    create: true
    overwrite: true
    name: monitoring-grafana-admin
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: alertmanager-telegram
  namespace: monitoring
spec:
  vaultAuthRef: monitoring
  mount: secret
  type: kv-v2
  path: monitoring/telegram
  refreshAfter: 1m
  hmacSecretData: true
  destination:
    create: true
    overwrite: true
    name: alertmanager-telegram
