---
helm_version: "v3.21.2"

helm_arch_map:
  x86_64: amd64
  aarch64: arm64

helm_arch: "{{ helm_arch_map[ansible_architecture] | default('amd64') }}"
ingress_nginx_chart_version: "4.15.1"
cert_manager_version: "v1.20.3"
local_path_version: "v0.0.36"
kube_prometheus_stack_chart_version: "87.2.1"
helm_diff_version: "v3.15.10"