---
- name: Configure Helm
  ansible.builtin.import_tasks: helm.yml
  tags: [helm]

- name: Configure ingress-nginx
  ansible.builtin.import_tasks: ingress-nginx.yml
  tags: [ingress_nginx]

- name: Configure cert-manager
  ansible.builtin.import_tasks: cert-manager.yml
  tags: [cert_manager]

- name: Configure storage
  ansible.builtin.import_tasks: storage.yml
  tags: [storage]

- name: Configure Vault
  ansible.builtin.import_tasks: vault.yml
  tags: [vault]

- name: Configure Vault Secrets Operator
  ansible.builtin.import_tasks: vault-secrets-operator.yml
  tags: [vault, vault_secrets_operator]

- name: Configure artifact attestation policies
  ansible.builtin.import_tasks: artifact-attestations.yml
  tags: [artifact_attestations]

- name: Configure Kyverno policies
  ansible.builtin.import_tasks: kyverno.yml
  tags: [kyverno]

- name: Configure Argo CD
  ansible.builtin.import_tasks: argocd.yml
  tags: [argocd]
