---
- name: Configure Helm
  ansible.builtin.import_tasks: helm.yml
  tags: [helm]

- name: Configure ingress-nginx
  ansible.builtin.import_tasks: ingress-nginx.yml
  tags: [ingress_nginx]

- name: Configure cert-manager
  ansible.builtin.import_tasks: cert-manager.yml
  tags: [cert_manager]

- name: Configure storage
  ansible.builtin.import_tasks: storage.yml
  tags: [storage]

- name: Configure monitoring
  ansible.builtin.import_tasks: monitoring.yml
  tags: [monitoring]

- name: Configure Argo CD
  ansible.builtin.import_tasks: argocd.yml
  tags: [argocd]
