---
- name: Copy Vault Secrets Operator values
  ansible.builtin.copy:
    src: vault-secrets-operator-values.yaml
    dest: /tmp/vault-secrets-operator-values.yaml
    mode: "0644"

- name: Install or upgrade Vault Secrets Operator
  kubernetes.core.helm:
    binary_path: /usr/local/bin/helm
    kubeconfig: /etc/kubernetes/admin.conf
    release_name: vault-secrets-operator
    chart_ref: vault-secrets-operator
    chart_repo_url: https://helm.releases.hashicorp.com
    chart_version: "{{ vault_secrets_operator_chart_version }}"
    release_namespace: vault-secrets-operator-system
    create_namespace: true
    values_files:
      - /tmp/vault-secrets-operator-values.yaml
    reset_values: true
    state: present
    wait: true
    atomic: true
    timeout: 5m0s
    history_max: 5
