---
- name: Bootstrap kubeadm Kubernetes cluster
  hosts: kube_cluster
  become: true
  roles:
    - kubeadm_cluster

- name: Install Kubernetes cluster addons
  hosts: kube_control_plane[0]
  become: true
  roles:
    - cluster_addons
  tags:
    - cluster_addons