controller:
  replicas: 1

  manager:
    logging:
      level: info

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 250m
        memory: 128Mi

defaultVaultConnection:
  enabled: false

defaultAuthMethod:
  enabled: false

telemetry:
  serviceMonitor:
    enabled: false